### ISSUE TITLE
Copy & Paste 

### ISSUE THREAD

**Issue by budalin** [cathalsurfs/ng-contenteditable#2]
While pasting the text in editable region that isn't show in editable region, instead of showing in toolbar. Please review this issue. see in attachment
![screen shot 2016-05-16 at 4 11 45 pm](https://cloud.githubusercontent.com/assets/1954113/15286107/09fda88a-1b81-11e6-9a0e-ca8d93a80161.png)

**Comment by cathalsurfs** [comment]
Hi budalin. Can you please attach the source (HTML and JS etc) for your project so that I can replicate. Also, please specify your browser version. Thanks.

**Comment by surfinky** [comment]
Hi @budalin, it would appear your bug is now fixed in the latest updates I have made. Please confirm.
